import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./Component/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <Navber></Navber>
     <div className="h-screen h-max-[600px] place-items-center place-content-center">
     {children}
     </div>
      <footer>
        <h3 className="text-center text-gray-400">My awsome component</h3>
      </footer>
    </body>
  </html>
  );
}
